global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "core-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]
  - job_name: "core-internal"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]
  - job_name: "api-gateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8083"]
  - job_name: "eureka"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8084"]
  - job_name: "notification-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8011"]
  - job_name: "notification-internal"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8013"]
  - job_name: "payment-internal"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8023"]
  - job_name: "chat-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8031"]