global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "core-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${CORE_API}"]

  - job_name: "core-internal"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${CORE_INTERNAL}"]

  - job_name: "api-gateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${API_GATEWAY}"]

  - job_name: "eureka"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${EUREKA}"]

  - job_name: "notification-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${NOTIFICATION_API}"]

  - job_name: "payment-internal"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${PAYMENT_INTERNAL}"]

  - job_name: "chat-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${CHAT_API}"]

  - job_name: "public ec2"
    static_configs:
      - targets: ["10.0.10.224:9100"]

  - job_name: "private ec2"
    static_configs:
      - targets: [ "10.0.11.243:9100" ]
